// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAD5nxf5PLTz5ZK4RZW_AVzLLX8kRAYYg',
    appId: '1:794567750274:web:50807b49be45f4b35ffa9b',
    messagingSenderId: '794567750274',
    projectId: 'userauthsms',
    authDomain: 'userauthsms.firebaseapp.com',
    storageBucket: 'userauthsms.appspot.com',
    measurementId: 'G-YK4467FFK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74Fuk6EUizH6sH9ZDqxWBhSEyAIrXZz0',
    appId: '1:794567750274:android:6f386634c6ccdf355ffa9b',
    messagingSenderId: '794567750274',
    projectId: 'userauthsms',
    storageBucket: 'userauthsms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5btC3MTNrMq2e7CZoHjJovtmyl3UN8MQ',
    appId: '1:794567750274:ios:41b5e6d6aaed21df5ffa9b',
    messagingSenderId: '794567750274',
    projectId: 'userauthsms',
    storageBucket: 'userauthsms.appspot.com',
    iosBundleId: 'com.example.sms',
  );
}
